import type { RentalDemoState, RentalInquiry, RentalService } from "../_types/rental";

const serviceBase = {
  imageUrls: [],
  visibility: "Public" as const,
  operationalStatus: "Ready for Use" as const,
  operatorRequirement: "Cooperative operator confirmation required",
  operationalNotes: "Final operating arrangements are confirmed during cooperative review.",
  safetyReminders: [
    "Follow the assigned operator's safety briefing.",
    "Keep children and bystanders away from the operating area.",
    "Report unsafe ground or weather conditions before operation.",
  ],
  lastMaintenanceDate: "2026-06-28",
  updatedAt: "2026-07-12T09:00:00+08:00",
};

export const rentalDemoServices: RentalService[] = [
  {
    ...serviceBase,
    serviceId: "SVC-TRC-001",
    name: "Farm Tractor",
    category: "Land Preparation",
    shortDescription: "Heavy field preparation support for qualified farm areas.",
    description: "A cooperative-managed farm tractor for plowing and primary land preparation, subject to site, operator, and schedule review.",
    availability: "By Schedule Only",
    unitOfUsage: "Operating session",
    suitableActivity: "Plowing and land preparation",
    capacity: "Confirmed after site review",
    serviceArea: "Approved areas within Nasugbu",
    upcomingBookings: 3,
  },
  {
    ...serviceBase,
    serviceId: "SVC-HTR-002",
    name: "Hand Tractor",
    category: "Land Preparation",
    shortDescription: "Compact land preparation for smaller and accessible plots.",
    description: "A compact hand tractor suitable for smaller plots where access and ground conditions allow safe operation.",
    availability: "Available",
    unitOfUsage: "Operating session",
    suitableActivity: "Tilling smaller farm plots",
    capacity: "Site dependent",
    serviceArea: "Nasugbu service barangays",
    upcomingBookings: 1,
  },
  {
    ...serviceBase,
    serviceId: "SVC-WPM-003",
    name: "Water Pump",
    category: "Irrigation",
    shortDescription: "Portable water movement support for approved agricultural use.",
    description: "A portable water pump for irrigation and agricultural water transfer, with setup requirements reviewed by NFFAC.",
    availability: "Limited Availability",
    unitOfUsage: "Scheduled use",
    suitableActivity: "Irrigation and agricultural water transfer",
    capacity: "Confirmed during inquiry review",
    serviceArea: "Accessible locations within Nasugbu",
    upcomingBookings: 2,
  },
  {
    ...serviceBase,
    serviceId: "SVC-GRC-004",
    name: "Grass Cutter",
    category: "Field Maintenance",
    shortDescription: "Field-edge and vegetation clearing support.",
    description: "Grass cutting equipment for farm maintenance, subject to terrain inspection and operator availability.",
    availability: "Available",
    unitOfUsage: "Operating session",
    suitableActivity: "Vegetation and field-edge clearing",
    capacity: "Location dependent",
    serviceArea: "Nasugbu service barangays",
    upcomingBookings: 1,
  },
  {
    ...serviceBase,
    serviceId: "SVC-FTL-005",
    name: "Farm Trailer",
    category: "Transport",
    shortDescription: "Short-distance hauling support for farm materials and produce.",
    description: "A farm trailer for approved agricultural hauling, paired with suitable towing equipment and route review.",
    availability: "By Schedule Only",
    unitOfUsage: "Scheduled trip",
    suitableActivity: "Farm materials and produce hauling",
    capacity: "Load subject to cooperative review",
    serviceArea: "Approved Nasugbu routes",
    upcomingBookings: 2,
  },
  {
    ...serviceBase,
    serviceId: "SVC-PSP-006",
    name: "Portable Sprayer",
    category: "Crop Care",
    shortDescription: "Portable application equipment for approved crop-care activities.",
    description: "A portable sprayer available for approved agricultural applications with required safety controls.",
    availability: "Available",
    unitOfUsage: "Scheduled use",
    suitableActivity: "Crop-care application",
    capacity: "Application dependent",
    serviceArea: "Nasugbu service barangays",
    upcomingBookings: 1,
  },
  {
    ...serviceBase,
    serviceId: "SVC-ATS-007",
    name: "Agricultural Transport Service",
    category: "Transport",
    shortDescription: "Coordinated agricultural transport for approved cooperative needs.",
    description: "A scheduled transport service for agricultural materials or produce, subject to route and load validation.",
    availability: "Limited Availability",
    unitOfUsage: "Approved trip",
    suitableActivity: "Agricultural logistics",
    capacity: "Vehicle and route dependent",
    serviceArea: "Approved routes in and around Nasugbu",
    upcomingBookings: 2,
  },
];

const inquiry = (values: Partial<RentalInquiry> & Pick<RentalInquiry, "inquiryId" | "rentalId" | "equipmentName" | "serviceId" | "status" | "paymentStatus">): RentalInquiry => ({
  requester: {
    requesterId: `REQ-${values.inquiryId.slice(-4)}`,
    fullName: "Juan Dela Cruz",
    requesterType: "Member",
    memberId: "MEM-2024-0081",
    contactNumber: "09171234567",
    email: "juan@example.test",
    completeAddress: "Purok 2, Lumbangan, Nasugbu, Batangas",
    barangay: "Lumbangan",
    municipality: "Nasugbu",
    preferredContactMethod: "SMS",
  },
  intendedUse: "Land preparation",
  preferredDate: "2026-07-18",
  alternativeDate: "2026-07-19",
  preferredStartTime: "08:00",
  estimatedDuration: "4 hours",
  estimatedUsage: "1.5 hectares",
  unitOfMeasurement: "Hectares",
  serviceLocation: "Sitio Maligaya farm lot",
  serviceBarangay: "Lumbangan",
  requestDescription: "Prepare the field for the next planting cycle.",
  specialInstructions: "Please confirm road access before dispatch.",
  additionalNotes: "Available by phone after 3 PM.",
  attachmentNames: [],
  scheduleStatus: "Confirmed",
  assignedReviewer: "TrackCOOP Admin",
  publicNote: "Your request is being coordinated with the equipment schedule.",
  submittedAt: "2026-07-10T09:20:00+08:00",
  updatedAt: "2026-07-12T10:30:00+08:00",
  ...values,
});

export const rentalDemoState: RentalDemoState = {
  services: rentalDemoServices,
  inquiries: [
    inquiry({ inquiryId: "RNT-2026-0041", rentalId: "RNT-2026-0041", serviceId: "SVC-TRC-001", equipmentName: "Farm Tractor", status: "Scheduled", paymentStatus: "Paid" }),
    inquiry({
      inquiryId: "RNT-2026-0042", rentalId: "RNT-2026-0042", serviceId: "SVC-WPM-003", equipmentName: "Water Pump", status: "Under Review", paymentStatus: "Pending",
      requester: { requesterId: "REQ-0042", fullName: "Maria Santos", requesterType: "Public or Non-member", contactNumber: "09181234567", email: "maria@example.test", completeAddress: "Wawa, Nasugbu, Batangas", barangay: "Wawa", municipality: "Nasugbu", preferredContactMethod: "Phone" },
      intendedUse: "Irrigation", preferredDate: "2026-07-21", serviceBarangay: "Wawa", serviceLocation: "Riverside farm, Wawa", publicNote: "NFFAC is reviewing service availability.", scheduleStatus: "Not scheduled",
    }),
    inquiry({
      inquiryId: "RNT-2026-0043", rentalId: "RNT-2026-0043", serviceId: "SVC-GRC-004", equipmentName: "Grass Cutter", status: "Completed", paymentStatus: "Paid",
      requester: { requesterId: "REQ-0043", fullName: "Pedro Reyes", requesterType: "Member", memberId: "MEM-2025-0042", contactNumber: "09191234567", completeAddress: "Bucana, Nasugbu, Batangas", barangay: "Bucana", municipality: "Nasugbu", preferredContactMethod: "SMS" },
      preferredDate: "2026-07-08", serviceBarangay: "Bucana", publicNote: "Rental completed. Your receipt is available.", scheduleStatus: "Completed",
    }),
    inquiry({
      inquiryId: "RNT-2026-0044", rentalId: "RNT-2026-0044", serviceId: "SVC-FTL-005", equipmentName: "Farm Trailer", status: "Awaiting Confirmation", paymentStatus: "Pending",
      requester: { requesterId: "REQ-0044", fullName: "Ana Mendoza", requesterType: "Public or Non-member", contactNumber: "09201234567", completeAddress: "Aga, Nasugbu, Batangas", barangay: "Aga", municipality: "Nasugbu", preferredContactMethod: "Phone" },
      preferredDate: "2026-07-22", serviceBarangay: "Aga", publicNote: "A proposed schedule is ready for confirmation.", scheduleStatus: "Proposed",
    }),
    inquiry({
      inquiryId: "RNT-2026-0045", rentalId: "RNT-2026-0045", serviceId: "SVC-PSP-006", equipmentName: "Portable Sprayer", status: "Payment Under Review", paymentStatus: "Under Review",
      requester: { requesterId: "REQ-0045", fullName: "Ramon Bautista", requesterType: "Member", memberId: "MEM-2023-0117", contactNumber: "09211234567", completeAddress: "Banilad, Nasugbu, Batangas", barangay: "Banilad", municipality: "Nasugbu", preferredContactMethod: "SMS" },
      preferredDate: "2026-07-24", serviceBarangay: "Banilad", publicNote: "Your payment proof is being validated.", scheduleStatus: "Awaiting payment",
    }),
  ],
  schedules: [
    { scheduleId: "SCH-0041", inquiryId: "RNT-2026-0041", rentalId: "RNT-2026-0041", serviceId: "SVC-TRC-001", equipmentName: "Farm Tractor", requesterName: "Juan Dela Cruz", requesterType: "Member", date: "2026-07-18", startTime: "08:00", endTime: "12:00", assignedOperator: "Roberto Garcia", serviceLocation: "Lumbangan farm lot", barangay: "Lumbangan", preparationMinutes: 30, travelMinutes: 30, bufferMinutes: 30, status: "Confirmed", paymentStatus: "Paid" },
    { scheduleId: "SCH-0044", inquiryId: "RNT-2026-0044", rentalId: "RNT-2026-0044", serviceId: "SVC-FTL-005", equipmentName: "Farm Trailer", requesterName: "Ana Mendoza", requesterType: "Public or Non-member", date: "2026-07-22", startTime: "09:00", endTime: "11:00", assignedOperator: "Luis Ramos", serviceLocation: "Aga collection point", barangay: "Aga", preparationMinutes: 20, travelMinutes: 30, bufferMinutes: 30, status: "Awaiting Confirmation", paymentStatus: "Pending" },
    { scheduleId: "SCH-MNT-01", inquiryId: "MAINTENANCE", rentalId: "MAINTENANCE", serviceId: "SVC-WPM-003", equipmentName: "Water Pump", requesterName: "NFFAC Maintenance", requesterType: "Member", date: "2026-07-20", startTime: "08:00", endTime: "12:00", serviceLocation: "NFFAC equipment yard", barangay: "Bilaran", preparationMinutes: 0, travelMinutes: 0, bufferMinutes: 0, status: "Maintenance", paymentStatus: "Pending" },
  ],
  payments: [
    { paymentId: "PAY-0041", rentalId: "RNT-2026-0041", requesterName: "Juan Dela Cruz", equipmentName: "Farm Tractor", scheduleDate: "2026-07-18", amount: 4500, paymentDate: "2026-07-12", paymentMethod: "Direct GCash", gcashReference: "GCASH-814729104", receiptNumber: "OR-RNT-0041", status: "Paid", notes: "Demonstration transaction record; not an official rental rate.", proofFileName: "payment-proof-0041.jpg", recordedBy: "NFFAC Bookkeeper", submittedAt: "2026-07-12T10:00:00+08:00" },
    { paymentId: "PAY-0045", rentalId: "RNT-2026-0045", requesterName: "Ramon Bautista", equipmentName: "Portable Sprayer", scheduleDate: "2026-07-24", amount: 750, paymentDate: "2026-07-12", paymentMethod: "GCash Reference Upload", gcashReference: "GCASH-550921870", status: "Under Review", notes: "Demonstration transaction record; validation pending.", proofFileName: "proof-0045.pdf", recordedBy: "Member upload", submittedAt: "2026-07-12T14:35:00+08:00" },
  ],
  expenses: [
    { expenseId: "EXP-001", rentalId: "RNT-2026-0041", expenseDate: "2026-07-12", equipmentName: "Farm Tractor", category: "Equipment Maintenance", amount: 2000, payee: "Nasugbu Farm Supply", paymentMethod: "Cash", referenceNumber: "EXP-REF-001", receiptFileName: "maintenance-receipt.jpg", description: "Demonstration maintenance transaction.", encodedBy: "NFFAC Bookkeeper" },
  ],
  receipts: [
    { receiptId: "RCT-0041", receiptNumber: "OR-RNT-0041", rentalId: "RNT-2026-0041", requesterName: "Juan Dela Cruz", requesterType: "Member", equipmentName: "Farm Tractor", scheduleDate: "2026-07-18", paymentDate: "2026-07-12", amountPaid: 4500, paymentMethod: "Direct GCash", referenceNumber: "GCASH-814729104", recordedBy: "NFFAC Bookkeeper", validationStatus: "Paid", verificationCode: "VRF-RNT-0041" },
  ],
  notifications: [
    { notificationId: "NTF-001", type: "Inquiry Received", title: "New rental inquiry received", message: "Maria Santos requested the Water Pump for July 21.", createdAt: "2026-07-12T15:20:00+08:00", rentalId: "RNT-2026-0042", read: false, href: "/rental/inquiries/RNT-2026-0042" },
    { notificationId: "NTF-002", type: "Payment Proof Received", title: "Payment proof needs validation", message: "Payment proof for RNT-2026-0045 is ready for review.", createdAt: "2026-07-12T14:35:00+08:00", rentalId: "RNT-2026-0045", read: false, href: "/rental/payments/PAY-0045/validate" },
    { notificationId: "NTF-003", type: "Schedule Confirmed", title: "Farm Tractor schedule confirmed", message: "RNT-2026-0041 is confirmed for July 18 at 8:00 AM.", createdAt: "2026-07-12T10:30:00+08:00", rentalId: "RNT-2026-0041", read: true, href: "/rental/inquiries/RNT-2026-0041" },
  ],
  auditEntries: [
    { auditId: "AUD-001", createdAt: "2026-07-12T10:30:00+08:00", user: "TrackCOOP Admin", role: "Admin", action: "Created Schedule", rentalId: "RNT-2026-0041", equipmentName: "Farm Tractor", recordAffected: "Schedule", newValue: "Confirmed — Jul 18, 8:00 AM", status: "Success", details: "Schedule confirmed after availability review." },
    { auditId: "AUD-002", createdAt: "2026-07-12T10:05:00+08:00", user: "NFFAC Bookkeeper", role: "Bookkeeper", action: "Confirmed Payment", rentalId: "RNT-2026-0041", equipmentName: "Farm Tractor", recordAffected: "Payment", previousValue: "Under Review", newValue: "Paid", status: "Success", details: "Payment validation completed and receipt generated." },
  ],
};
