"use client";

import { BarChart3, CheckCircle2, CircleDollarSign, HandCoins, Percent, Tractor, TrendingUp } from "lucide-react";
import Link from "next/link";
import { rentalRepository } from "../_lib/rentalRepository";
import { formatPeso } from "../_lib/rentalFormatting";
import { useRentalData } from "../_hooks/useRentalData";
import { RentalAccessGate } from "./RentalAccessGate";
import { RentalChartCard } from "./RentalChartCard";
import { RentalMetricCard } from "./RentalMetricCard";
import { RentalLoadingState } from "./RentalStates";
import { RentalPageHeader } from "./RentalPageHeader";

export function RentalAnalyticsView() {
  const { data, loading } = useRentalData(() => rentalRepository.getRentalAnalytics(), []);
  return <RentalAccessGate capability="analytics"><RentalPageHeader title="Rental income analytics" description="Rental income and expenses contribute to the TrackCOOP Financial Management and Analytics module." />{loading || !data ? <RentalLoadingState /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><RentalMetricCard label="Total Rental Income" value={formatPeso(data.totalIncome)} icon={CircleDollarSign} /><RentalMetricCard label="Rental Expenses" value={formatPeso(data.totalExpenses)} icon={HandCoins} /><RentalMetricCard label="Net Rental Income" value={formatPeso(data.netIncome)} icon={TrendingUp} /><RentalMetricCard label="Average / Completed" value={formatPeso(data.averageIncomePerCompletedRental)} icon={BarChart3} /><RentalMetricCard label="Completed Rentals" value={data.completedRentals} icon={CheckCircle2} /><RentalMetricCard label="Payment Completion Rate" value={`${data.paymentCompletionRate}%`} icon={Percent} /><RentalMetricCard label="Most Profitable Equipment" value={data.mostProfitableEquipment} icon={Tractor} /><RentalMetricCard label="Highest Demand Equipment" value={data.highestDemandEquipment} icon={Tractor} /></section><section className="mt-5 grid gap-5 xl:grid-cols-2"><RentalChartCard title="Monthly Rental Income" description="Validated internal rental income transactions." data={data.monthlyIncome} format={formatPeso} /><RentalChartCard title="Income by Equipment" description="Demonstration income distribution by rental service." data={data.incomeByEquipment} format={formatPeso} /><RentalChartCard title="Income versus Expenses" description="Monthly internal transaction comparison." data={[...data.monthlyIncome.slice(-3), ...data.expensesByMonth.map((item) => ({ label: `${item.label} expenses`, value: item.value }))]} format={formatPeso} /><RentalChartCard title="Payment Status Breakdown" description="Share of completed and pending validations." data={[{ label: "Paid", value: data.paymentCompletionRate }, { label: "Pending", value: 100 - data.paymentCompletionRate }]} format={(value) => `${value}%`} /></section><section className="mt-5 rounded-2xl bg-[#123d2a] p-6 text-white"><h2 className="text-xl font-extrabold">Equipment utilization deep dive</h2><p className="mt-2 text-sm text-white/70">Compare usage, downtime, availability, bookings, and request conversion by equipment.</p><Link href="/rental/analytics/utilization" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-[#e7efbd] px-5 text-sm font-bold text-[#123d2a]">Open Utilization Analytics</Link></section></>}</RentalAccessGate>;
}

export function RentalUtilizationView() {
  const { data = [], loading } = useRentalData(() => rentalRepository.getEquipmentUtilization(), []);
  const totalBookings = data.reduce((sum, item) => sum + item.bookings, 0);
  return <RentalAccessGate capability="analytics"><RentalPageHeader title="Equipment utilization" description="Utilization Rate shows how often equipment was scheduled compared with the time it was available." />{loading ? <RentalLoadingState /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><RentalMetricCard label="Total usage units" value="126" note="Demo operating sessions and trips" icon={Tractor} /><RentalMetricCard label="Completed rentals" value="18" icon={CheckCircle2} /><RentalMetricCard label="Cancelled rentals" value="2" icon={BarChart3} /><RentalMetricCard label="Availability percentage" value="86%" icon={Percent} /><RentalMetricCard label="Utilization rate" value="64%" icon={TrendingUp} /><RentalMetricCard label="Maintenance days" value="8" icon={HandCoins} /><RentalMetricCard label="Idle days" value="42" icon={BarChart3} /><RentalMetricCard label="Upcoming bookings" value={totalBookings} icon={Tractor} /></section><section className="mt-5 grid gap-5 xl:grid-cols-2"><RentalChartCard title="Utilization by Equipment" description="Percentage of available time that was scheduled." data={data.map((item) => ({ label: item.label, value: item.usage }))} format={(value) => `${value}%`} /><RentalChartCard title="Equipment Downtime" description="Inverse availability indicator for plain-language comparison." data={data.map((item) => ({ label: item.label, value: 100 - item.availability }))} format={(value) => `${value}%`} /><RentalChartCard title="Rental Count by Equipment" description="Confirmed upcoming bookings in the selected period." data={data.map((item) => ({ label: item.label, value: item.bookings }))} /><RentalChartCard title="Request-to-Completion Conversion" description="Demonstration share of requests progressing to completion." data={[{ label: "Requested", value: 28 }, { label: "Approved", value: 22 }, { label: "Scheduled", value: 20 }, { label: "Completed", value: 18 }]} /></section><div className="mt-5 grid gap-3 sm:grid-cols-2"><Explanation title="Utilization Rate" text="How often equipment was scheduled compared with the time it was available." /><Explanation title="Availability Percentage" text="How much planned service time remained usable after maintenance and outages." /><Explanation title="Downtime" text="Days when equipment could not be offered due to maintenance or operational status." /><Explanation title="Conversion" text="How many inquiries progressed from request through cooperative review to completion." /></div></>}</RentalAccessGate>;
}
function Explanation({ title, text }: { title: string; text: string }) { return <article className="rounded-2xl border border-[#dce7d6] bg-white p-5"><h2 className="font-extrabold text-[#123d2a]">{title}</h2><p className="mt-1 text-sm leading-6 text-[#66756c]">{text}</p></article>; }
