"use client";

import { CalendarPlus, Mail, Phone, WalletCards } from "lucide-react";
import Link from "next/link";
import { rentalRepository } from "../_lib/rentalRepository";
import { formatRentalDate } from "../_lib/rentalFormatting";
import { useRentalData } from "../_hooks/useRentalData";
import { RentalAccessGate } from "./RentalAccessGate";
import { RentalLoadingState } from "./RentalStates";
import { RentalPageHeader } from "./RentalPageHeader";
import { RentalPaymentStatusBadge } from "./RentalPaymentStatusBadge";
import { RentalStatusBadge } from "./RentalStatusBadge";

export function RentalRequestDetails({ inquiryId }: { inquiryId: string }) {
  const { data, loading } = useRentalData(() => rentalRepository.getRentalInquiryById(inquiryId), [inquiryId]);
  if (loading) return <RentalLoadingState />;
  if (!data) return <div className="rounded-2xl border bg-white p-8 text-center"><h1 className="text-2xl font-bold">Inquiry not found</h1></div>;
  return <RentalAccessGate capability="inquiries"><RentalPageHeader eyebrow={data.inquiryId} title={`${data.equipmentName} rental request`} description={`${data.requester.fullName} · ${data.requester.requesterType} · submitted ${formatRentalDate(data.submittedAt)}`} /><div className="mb-5 flex flex-wrap gap-2"><RentalStatusBadge status={data.status} /><RentalPaymentStatusBadge status={data.paymentStatus} /><span className="rounded-full border bg-white px-3 py-1 text-xs font-bold">Schedule: {data.scheduleStatus}</span></div><div className="grid gap-5 xl:grid-cols-[1fr_.7fr]"><div className="grid gap-5"><DetailCard title="Requester information" rows={[["Full name", data.requester.fullName], ["Member ID", data.requester.memberId ?? "Not applicable"], ["Contact", data.requester.contactNumber], ["Email", data.requester.email ?? "Not provided"], ["Address", data.requester.completeAddress], ["Barangay", data.requester.barangay], ["Requester type", data.requester.requesterType]]} /><DetailCard title="Request information" rows={[["Equipment", data.equipmentName], ["Intended use", data.intendedUse], ["Preferred date", formatRentalDate(data.preferredDate, true)], ["Alternative date", formatRentalDate(data.alternativeDate, true)], ["Time", data.preferredStartTime ?? "Not provided"], ["Estimated duration", data.estimatedDuration], ["Estimated area / usage", `${data.estimatedUsage} ${data.unitOfMeasurement}`], ["Service location", `${data.serviceLocation}, ${data.serviceBarangay}`], ["Description", data.requestDescription]]} /><DetailCard title="Attachments and notes" rows={[["Request documents", data.attachmentNames.join(", ") || "None"], ["Public requester note", data.additionalNotes ?? "None"], ["Internal staff note", data.internalNote ?? "None"], ["Latest public note", data.publicNote]]} /></div><aside className="grid content-start gap-5"><section className="rounded-2xl border border-[#dce7d6] bg-white p-5"><h2 className="text-lg font-extrabold text-[#123d2a]">Quick actions</h2><div className="mt-4 grid gap-2"><Action href={`/rental/inquiries/${data.inquiryId}/review`} label="Review Request" icon={Mail} /><Action href={`/rental/schedule/new?inquiry=${data.inquiryId}`} label="Create Schedule" icon={CalendarPlus} /><Action href={`/rental/payments/new?rental=${data.rentalId}`} label="Record Payment" icon={WalletCards} /><a href={`tel:${data.requester.contactNumber}`} className="flex min-h-11 items-center gap-3 rounded-xl border px-4 text-sm font-bold text-[#365f4a]"><Phone className="size-4" />Contact Requester</a></div></section><RentalRequestTimeline status={data.status} /></aside></div></RentalAccessGate>;
}
function DetailCard({ title, rows }: { title: string; rows: string[][] }) { return <section className="rounded-2xl border border-[#dce7d6] bg-white p-5"><h2 className="text-lg font-extrabold text-[#123d2a]">{title}</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{rows.map(([term, value]) => <div key={term} className={value.length > 60 ? "sm:col-span-2" : ""}><dt className="text-xs font-bold uppercase text-[#78857d]">{term}</dt><dd className="mt-1 text-sm font-semibold leading-6 text-[#365f4a]">{value}</dd></div>)}</dl></section>; }
function Action({ href, label, icon: Icon }: { href: string; label: string; icon: typeof Mail }) { return <Link href={href} className="flex min-h-11 items-center gap-3 rounded-xl border px-4 text-sm font-bold text-[#365f4a]"><Icon className="size-4" />{label}</Link>; }
export function RentalRequestTimeline({ status }: { status: string }) { const steps = ["Inquiry submitted", "Under review", "Schedule proposed", "Requester confirmed", "Payment recorded", "Rental started", "Rental completed"]; const current = status === "Completed" ? 7 : status === "In Progress" ? 6 : status.includes("Payment") ? 5 : status === "Scheduled" ? 4 : status === "Under Review" ? 2 : 1; return <section className="rounded-2xl border border-[#dce7d6] bg-white p-5"><h2 className="text-lg font-extrabold text-[#123d2a]">Request timeline</h2><ol className="mt-4 grid gap-1">{steps.map((step, index) => <li key={step} className="flex gap-3"><span className={`mt-1 grid size-6 shrink-0 place-items-center rounded-full text-xs font-bold ${index < current ? "bg-[#1f6b43] text-white" : "bg-[#e8eee5] text-[#75837a]"}`}>{index + 1}</span><span className={`pb-5 text-sm font-semibold ${index < current ? "text-[#284735]" : "text-[#8a958e]"}`}>{step}</span></li>)}</ol></section>; }
