"use client";

import { CalendarCheck, CheckCircle2, Clock3, CreditCard, FileUp, Plus, ReceiptText, RotateCcw, Tractor } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { rentalRepository } from "../_lib/rentalRepository";
import { formatRentalDate } from "../_lib/rentalFormatting";
import { validateUpload } from "../_lib/rentalValidation";
import type { RentalInquiry } from "../_types/rental";
import { useRentalData } from "../_hooks/useRentalData";
import { RentalAccessGate } from "./RentalAccessGate";
import { RentalInquiryForm } from "./RentalInquiryForm";
import { RentalInquiryReview } from "./RentalInquiryReview";
import { RentalMetricCard } from "./RentalMetricCard";
import { RentalPageHeader } from "./RentalPageHeader";
import { RentalPaymentStatusBadge } from "./RentalPaymentStatusBadge";
import { RentalRequestTimeline } from "./RentalRequestDetails";
import { RentalLoadingState } from "./RentalStates";
import { RentalStatusBadge } from "./RentalStatusBadge";

const currentDemoMember = "Juan Dela Cruz";
const ownRequests = (items: RentalInquiry[]) => items.filter((item) => item.requester.fullName === currentDemoMember);

export function RentalMemberHome() {
  const { data, loading } = useRentalData(async () => ({ inquiries: ownRequests(await rentalRepository.getRentalInquiries()), services: await rentalRepository.getRentalServices() }), []);
  return <RentalAccessGate capability="member"><RentalPageHeader eyebrow={`Welcome, ${currentDemoMember}`} title="My rental area" description="Browse available services, follow your requests, confirm schedules, submit payment proof, and access receipts." action={{ href: "/rental/member/requests/new", label: "New Rental Request", icon: Plus }} />{loading || !data ? <RentalLoadingState /> : <><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><RentalMetricCard label="Available services" value={data.services.filter((item) => item.availability !== "Unavailable").length} icon={Tractor} /><RentalMetricCard label="Active requests" value={data.inquiries.filter((item) => !["Completed", "Cancelled", "Rejected"].includes(item.status)).length} icon={Clock3} /><RentalMetricCard label="Upcoming schedule" value={data.inquiries.find((item) => item.status === "Scheduled") ? formatRentalDate(data.inquiries.find((item) => item.status === "Scheduled")?.preferredDate) : "None"} icon={CalendarCheck} /><RentalMetricCard label="Completed rentals" value={data.inquiries.filter((item) => item.status === "Completed").length} icon={CheckCircle2} /></section><section className="mt-5 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-[#dce7d6] bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-extrabold text-[#123d2a]">My active requests</h2><Link href="/rental/member/requests" className="text-sm font-bold text-[#1f6b43]">View all</Link></div><div className="mt-4 grid gap-3">{data.inquiries.map((item) => <Link href={`/rental/member/requests/${item.rentalId}`} key={item.rentalId} className="flex flex-col gap-3 rounded-xl border p-4 sm:flex-row sm:items-center"><div className="flex-1"><p className="font-mono text-xs text-[#75837a]">{item.rentalId}</p><h3 className="font-extrabold text-[#123d2a]">{item.equipmentName}</h3><p className="text-xs text-[#66756c]">Preferred {formatRentalDate(item.preferredDate)}</p></div><RentalStatusBadge status={item.status} /><RentalPaymentStatusBadge status={item.paymentStatus} /></Link>)}</div></article><article className="rounded-2xl bg-[#123d2a] p-6 text-white"><h2 className="text-xl font-extrabold">Important update</h2><p className="mt-3 text-sm leading-6 text-white/75">Rental pricing and policies remain pending final cooperative validation. NFFAC will confirm final cost, gasoline responsibility, discounts, cancellation, and rescheduling conditions.</p><Link href="/rental" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#e7efbd] px-5 text-sm font-bold text-[#123d2a]">Browse Services</Link></article></section></>}</RentalAccessGate>;
}

export function RentalMemberRequests() {
  const { data = [], loading } = useRentalData(async () => ownRequests(await rentalRepository.getRentalInquiries()), []);
  return <RentalAccessGate capability="member"><RentalPageHeader title="My rental requests" description="Only rental records belonging to the current member are shown." action={{ href: "/rental/member/requests/new", label: "New Request", icon: Plus }} />{loading ? <RentalLoadingState /> : <div className="grid gap-3">{data.map((item) => <article key={item.rentalId} className="grid gap-4 rounded-2xl border border-[#dce7d6] bg-white p-5 md:grid-cols-[1fr_1fr_1fr_auto] md:items-center"><div><p className="font-mono text-xs text-[#75837a]">{item.rentalId}</p><h2 className="font-extrabold text-[#123d2a]">{item.equipmentName}</h2></div><div><p className="text-xs font-bold uppercase text-[#75837a]">Preferred / Confirmed date</p><p className="text-sm font-bold">{formatRentalDate(item.preferredDate)}</p><p className="text-xs">{item.scheduleStatus}</p></div><div className="flex flex-wrap gap-2"><RentalStatusBadge status={item.status} /><RentalPaymentStatusBadge status={item.paymentStatus} /></div><Link href={`/rental/member/requests/${item.rentalId}`} className="inline-flex min-h-11 items-center justify-center rounded-xl bg-[#1f6b43] px-4 text-sm font-bold text-white">View Request</Link></article>)}</div>}</RentalAccessGate>;
}

export function RentalMemberNewRequest() {
  const [review, setReview] = useState(false);
  useEffect(() => {
    const timer = window.setTimeout(() => setReview(new URLSearchParams(window.location.search).get("review") === "1"), 0);
    return () => window.clearTimeout(timer);
  }, []);
  return <RentalAccessGate capability="member"><RentalPageHeader title={review ? "Review member rental request" : "New member rental request"} description="Your member identity will be matched by the TrackCOOP authentication adapter before API submission." />{review ? <RentalInquiryReview member /> : <RentalInquiryForm member />}</RentalAccessGate>;
}

export function RentalMemberRequestDetails({ rentalId }: { rentalId: string }) {
  const requestData = useRentalData(async () => (await rentalRepository.getRentalInquiries()).find((item) => item.rentalId === rentalId && item.requester.fullName === currentDemoMember), [rentalId]);
  if (requestData.loading) return <RentalLoadingState />;
  const item = requestData.data;
  if (!item) return <RentalAccessGate capability="member"><div className="rounded-2xl border bg-white p-8 text-center"><h1 className="text-2xl font-bold">Request not found in this member account</h1></div></RentalAccessGate>;
  const confirm = async () => { await rentalRepository.updateRentalStatus(item.inquiryId, "Scheduled"); requestData.refresh(); };
  return <RentalAccessGate capability="member"><RentalPageHeader eyebrow={item.rentalId} title={item.equipmentName} description={`Preferred date ${formatRentalDate(item.preferredDate, true)} · ${item.serviceBarangay}`} /><div className="grid gap-5 xl:grid-cols-[1fr_.7fr]"><div className="grid gap-5"><section className="rounded-2xl border border-[#dce7d6] bg-white p-5"><h2 className="text-lg font-extrabold text-[#123d2a]">Request information</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2">{[["Intended use", item.intendedUse], ["Estimated usage", `${item.estimatedUsage} ${item.unitOfMeasurement}`], ["Service location", item.serviceLocation], ["Preferred date", formatRentalDate(item.preferredDate)], ["Confirmed schedule", item.scheduleStatus], ["Cooperative message", item.publicNote]].map(([term, value]) => <div key={term}><dt className="text-xs font-bold uppercase text-[#75837a]">{term}</dt><dd className="mt-1 text-sm font-bold leading-6 text-[#365f4a]">{value}</dd></div>)}</dl></section><section className="rounded-2xl border border-[#dce7d6] bg-white p-5"><h2 className="text-lg font-extrabold text-[#123d2a]">Payment instructions</h2><p className="mt-2 text-sm leading-6 text-[#66756c]">Wait for NFFAC to confirm the approved cost and payment instructions. Do not rely on demonstration amounts as official pricing.</p><div className="mt-4 flex flex-wrap gap-2"><Link href={`/rental/member/requests/${rentalId}/payment`} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#1f6b43] px-5 text-sm font-bold text-white"><CreditCard className="size-4" />Upload Payment Proof</Link><Link href={`/rental/member/requests/${rentalId}/reschedule`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-5 text-sm font-bold"><RotateCcw className="size-4" />Request Reschedule</Link>{item.paymentStatus === "Paid" && <Link href={`/rental/receipts/RCT-${rentalId.slice(-4)}`} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-5 text-sm font-bold"><ReceiptText className="size-4" />View Receipt</Link>}</div></section></div><aside className="grid content-start gap-5"><div className="rounded-2xl border border-[#dce7d6] bg-white p-5"><div className="flex flex-wrap gap-2"><RentalStatusBadge status={item.status} /><RentalPaymentStatusBadge status={item.paymentStatus} /></div>{item.status === "Awaiting Confirmation" && <button onClick={() => void confirm()} className="mt-4 min-h-11 w-full rounded-xl bg-[#1f6b43] px-4 text-sm font-bold text-white">Confirm Proposed Schedule</button>}</div><RentalRequestTimeline status={item.status} /></aside></div></RentalAccessGate>;
}

export function RentalMemberPaymentProof({ rentalId }: { rentalId: string }) {
  const router = useRouter();
  const [amount, setAmount] = useState(""); const [date, setDate] = useState("2026-07-13"); const [reference, setReference] = useState(""); const [file, setFile] = useState<File>(); const [notes, setNotes] = useState(""); const [error, setError] = useState<string>(); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); const issue = validateUpload(file); if (issue || !file) { setError(issue ?? "Payment proof is required."); return; } setSaving(true); await rentalRepository.uploadRentalPaymentProof(rentalId, file, reference); window.alert("Payment proof submitted. Status: Payment Under Review."); router.push(`/rental/member/requests/${rentalId}`); };
  return <RentalAccessGate capability="member"><RentalPageHeader eyebrow={rentalId} title="Upload payment proof" description="Submit proof only after receiving the cooperative-approved amount and payment instructions." /><form onSubmit={submit} className="mx-auto max-w-2xl rounded-2xl border border-[#dce7d6] bg-white p-5"><div className="rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-900">Verify the approved rental cost before submitting payment proof.</div>{error && <p role="alert" className="mt-4 text-sm font-bold text-red-700">{error}</p>}<div className="mt-5 grid gap-4 sm:grid-cols-2"><MemberField label="Rental ID"><input value={rentalId} readOnly /></MemberField><MemberField label="Amount"><input required type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} /></MemberField><MemberField label="Payment date"><input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></MemberField><MemberField label="GCash reference"><input required value={reference} onChange={(event) => setReference(event.target.value)} /></MemberField><MemberField label="Payment proof" wide><input required type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={(event) => setFile(event.target.files?.[0])} /></MemberField><MemberField label="Notes" wide><textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} /></MemberField></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="min-h-11 px-5 font-bold text-[#66756c]">Cancel</button><button disabled={saving} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#1f6b43] px-6 font-bold text-white"><FileUp className="size-4" />{saving ? "Uploading…" : "Submit Proof"}</button></div></form></RentalAccessGate>;
}

export function RentalMemberReschedule({ rentalId }: { rentalId: string }) {
  const router = useRouter(); const { data } = useRentalData(() => rentalRepository.getRentalInquiryById(rentalId), [rentalId]); const [date, setDate] = useState(""); const [alternative, setAlternative] = useState(""); const [reason, setReason] = useState(""); const [note, setNote] = useState("");
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!window.confirm("Submit this reschedule request for admin review and conflict checking?")) return; await rentalRepository.reviewRentalInquiry(rentalId, "Rescheduled", `Reschedule requested for ${date}; NFFAC will review equipment availability.`, `${reason}\nAlternative: ${alternative}\n${note}`); router.push(`/rental/member/requests/${rentalId}`); };
  return <RentalAccessGate capability="member"><RentalPageHeader eyebrow={rentalId} title="Request reschedule" description="Rescheduling approval depends on equipment availability and cooperative policy." /><form onSubmit={submit} className="mx-auto max-w-2xl rounded-2xl border border-[#dce7d6] bg-white p-5"><div className="grid gap-4 sm:grid-cols-2"><MemberField label="Current schedule" wide><input value={data ? `${formatRentalDate(data.preferredDate)} · ${data.preferredStartTime ?? "Time pending"}` : "Loading…"} readOnly /></MemberField><MemberField label="Requested date"><input required type="date" value={date} onChange={(event) => setDate(event.target.value)} /></MemberField><MemberField label="Alternative date"><input required type="date" value={alternative} onChange={(event) => setAlternative(event.target.value)} /></MemberField><MemberField label="Reason" wide><textarea required rows={3} value={reason} onChange={(event) => setReason(event.target.value)} /></MemberField><MemberField label="Additional note" wide><textarea rows={3} value={note} onChange={(event) => setNote(event.target.value)} /></MemberField></div><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => router.back()} className="min-h-11 px-5 font-bold text-[#66756c]">Cancel</button><button className="min-h-11 rounded-xl bg-[#1f6b43] px-6 font-bold text-white">Submit Reschedule Request</button></div></form></RentalAccessGate>;
}
function MemberField({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactElement }) { return <label className={`grid gap-1.5 text-sm font-bold text-[#365f4a] ${wide ? "sm:col-span-2" : ""}`}>{label}<span className="[&>*]:min-h-11 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-[#d5e1d0] [&>*]:bg-white [&>*]:p-3 [&>*]:text-sm [&>*]:font-normal">{children}</span></label>; }
