"use client";

import { AlertTriangle, X } from "lucide-react";
import { useEffect } from "react";
import type { ScheduleConflict } from "../_types/rental";

export function RentalConflictModal({ conflict, onClose, onSelect }: { conflict: ScheduleConflict; onClose: () => void; onSelect: (slot: string) => void }) {
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onClose]);
  return <div className="fixed inset-0 z-[80] grid place-items-center p-4"><button aria-label="Close conflict warning" onClick={onClose} className="absolute inset-0 bg-black/55" /><section role="alertdialog" aria-modal="true" aria-labelledby="conflict-title" className="relative max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><button aria-label="Close" onClick={onClose} className="absolute right-4 top-4 grid size-10 place-items-center rounded-xl bg-[#f2f4ef]"><X className="size-5" /></button><AlertTriangle className="size-10 text-amber-700" /><h2 id="conflict-title" className="mt-3 text-2xl font-extrabold text-[#123d2a]">Schedule conflict detected</h2><p className="mt-2 text-sm text-[#66756c]">The proposed equipment, operator, maintenance, preparation, or buffer period overlaps an existing commitment.</p><ul className="mt-5 grid gap-3">{conflict.reasons.map((reason) => <li key={reason} className="rounded-xl bg-amber-50 p-4 text-sm font-semibold text-amber-900">{reason}</li>)}</ul>{conflict.conflictingSchedules.map((item) => <dl key={item.scheduleId} className="mt-4 grid grid-cols-2 gap-3 rounded-xl border p-4 text-sm"><div><dt className="text-xs text-[#75837a]">Equipment</dt><dd className="font-bold">{item.equipmentName}</dd></div><div><dt className="text-xs text-[#75837a]">Existing requester</dt><dd className="font-bold">{item.requesterName}</dd></div><div><dt className="text-xs text-[#75837a]">Conflict period</dt><dd className="font-bold">{item.date}, {item.startTime}–{item.endTime}</dd></div><div><dt className="text-xs text-[#75837a]">Status</dt><dd className="font-bold">{item.status}</dd></div></dl>)}<h3 className="mt-5 font-extrabold text-[#123d2a]">Suggested available time slots</h3><div className="mt-2 flex flex-wrap gap-2">{conflict.suggestedSlots.map((slot) => <button key={slot} onClick={() => onSelect(slot)} className="min-h-11 rounded-xl border border-[#9fbea2] bg-[#eef5eb] px-4 text-sm font-bold text-[#365f4a]">Select {slot}</button>)}</div><div className="mt-6 flex flex-wrap justify-end gap-2"><button onClick={onClose} className="min-h-11 rounded-xl border px-4 text-sm font-bold">Return to Schedule</button><button className="min-h-11 rounded-xl border px-4 text-sm font-bold">Choose Another Equipment</button><button onClick={() => window.alert("Authorization, a reason, confirmation, and an audit entry are required for override.")} className="min-h-11 rounded-xl bg-[#123d2a] px-4 text-sm font-bold text-white">Override With Authorization</button></div></section></div>;
}
