import type { DocumentAccessLevel, ReportDefinition } from "./records-types";

export const DOCUMENT_CATEGORIES = [
  "MEMBERSHIP",
  "FINANCIAL",
  "RENTAL",
  "POS_AND_SALES",
  "INVENTORY",
  "RECEIPT",
  "CERTIFICATE",
  "WAIVER",
  "COOPERATIVE_PLAN",
  "BUSINESS_PLAN",
  "ANNUAL_PLAN",
  "AGENCY_REPORT",
  "ANNOUNCEMENT",
  "MEETING_RECORD",
  "POLICY",
  "LEGAL",
  "AUDIT",
  "OTHER",
] as const;

export const DOCUMENT_TYPES = [
  "Receipt",
  "Certificate",
  "Waiver",
  "Financial Document",
  "Annual Plan",
  "Business Plan",
  "Agency Report",
  "Public Document",
  "Other",
] as const;

export const DOCUMENT_ACCESS_LEVELS: Array<{
  value: DocumentAccessLevel;
  label: string;
}> = [
  { value: "PUBLIC", label: "Public" },
  { value: "MEMBER_ONLY", label: "Member only" },
  { value: "ADMIN_ONLY", label: "Chairman/Admin only" },
  { value: "BOOKKEEPER_ONLY", label: "Bookkeeper only" },
];

export const RELATED_MODULES = [
  "MEMBERSHIP",
  "MEMBERSHIP_APPLICATION",
  "MEMBER_PROFILE",
  "SHARE_CAPITAL",
  "PAYMENT",
  "RECEIPT",
  "FINANCIAL_LEDGER",
  "RENTAL_ASSET",
  "RENTAL_BOOKING",
  "RENTAL_PAYMENT",
  "RENTAL_EXPENSE",
  "POS_SALE",
  "PRODUCT",
  "ORDER",
  "INVENTORY",
  "EXPENSE",
  "ANNOUNCEMENT",
  "REPORT",
  "COOPERATIVE_PLAN",
  "AGENCY_SUBMISSION",
  "AUDIT_RECORD",
] as const;

export const MAX_DOCUMENT_FILE_SIZE = 10 * 1024 * 1024;

const staffRoles = ["chairman", "bookkeeper"] as const;
const chairmanOnly = ["chairman"] as const;
const standardDates = ["dateFrom", "dateTo"] as const;

function report(
  key: string,
  name: string,
  category: ReportDefinition["category"],
  description: string,
  dataSource: string,
  filters: ReportDefinition["filters"],
  roles: ReportDefinition["allowedRoles"] = [...staffRoles],
): ReportDefinition {
  return {
    key,
    name,
    category,
    description,
    dataSource,
    filters,
    allowedRoles: roles,
  };
}

export const REPORT_CATALOG: ReportDefinition[] = [
  report(
    "financial-summary",
    "Financial Summary",
    "FINANCIAL",
    "Confirmed posted income, expense, and net result.",
    "Financial ledger",
    [...standardDates],
  ),
  report(
    "cash-in-out",
    "Cash In and Cash Out",
    "FINANCIAL",
    "Posted inflows and outflows for the selected period.",
    "Financial ledger",
    [...standardDates],
  ),
  report(
    "financial-ledger",
    "Financial Ledger",
    "FINANCIAL",
    "Detailed posted ledger entries and source modules.",
    "Financial ledger and categories",
    [...standardDates],
  ),
  report(
    "income-by-source",
    "Income by Source",
    "FINANCIAL",
    "Confirmed income grouped by its source module.",
    "Financial ledger",
    [...standardDates],
  ),
  report(
    "expense-by-category",
    "Expense by Category",
    "FINANCIAL",
    "Confirmed expenses grouped by ledger category.",
    "Financial ledger and categories",
    [...standardDates],
  ),
  report(
    "payment-status",
    "Payment Status",
    "FINANCIAL",
    "Submitted payment references grouped by validation state.",
    "Payment references",
    [...standardDates, "paymentStatus"],
  ),
  report(
    "payment-method",
    "Payment Method",
    "FINANCIAL",
    "Payment references grouped by provider.",
    "Payment references",
    [...standardDates, "paymentMethod"],
  ),
  report(
    "receipt-register",
    "Receipt Register",
    "FINANCIAL",
    "Receipt documents issued through TrackCOOP.",
    "Documents",
    [...standardDates],
  ),
  report(
    "reconciliation-exceptions",
    "Reconciliation Exceptions",
    "FINANCIAL",
    "Validated payments without a posted ledger effect and mismatched links.",
    "Payment references and ledger",
    [...standardDates],
  ),
  report(
    "refund-reversal",
    "Refund and Reversal Report",
    "FINANCIAL",
    "Reversed, corrected, voided, or refunded records.",
    "Financial ledger and payments",
    [...standardDates],
  ),
  report(
    "annual-financial-summary",
    "Annual Financial Summary",
    "FINANCIAL",
    "Confirmed annual income, expense, and net totals.",
    "Financial ledger",
    ["year"],
  ),
  report(
    "monthly-financial-summary",
    "Monthly Financial Summary",
    "FINANCIAL",
    "Confirmed month-by-month financial totals.",
    "Financial ledger",
    ["year"],
  ),

  report(
    "member-directory",
    "Member Directory",
    "MEMBERSHIP",
    "Privacy-conscious active cooperative member directory.",
    "Member profiles",
    ["barangay", "sector", "membershipType"],
    [...chairmanOnly],
  ),
  report(
    "membership-applications",
    "Membership Applications",
    "MEMBERSHIP",
    "Application volume and review status.",
    "Membership applications",
    [...standardDates, "barangay", "membershipType"],
    [...chairmanOnly],
  ),
  report(
    "membership-growth",
    "Membership Growth",
    "MEMBERSHIP",
    "Approved membership growth by month.",
    "Member profiles",
    [...standardDates],
    [...chairmanOnly],
  ),
  report(
    "members-by-barangay",
    "Members by Barangay",
    "MEMBERSHIP",
    "Approved members grouped by barangay.",
    "Member profiles",
    ["membershipType"],
    [...chairmanOnly],
  ),
  report(
    "members-by-sector",
    "Members by Sector",
    "MEMBERSHIP",
    "Approved members grouped by agricultural sector.",
    "Member profiles",
    ["membershipType"],
    [...chairmanOnly],
  ),
  report(
    "associate-members",
    "Associate Members",
    "MEMBERSHIP",
    "Current associate-member records.",
    "Member profiles",
    ["barangay", "sector"],
    [...chairmanOnly],
  ),
  report(
    "true-members",
    "True Members",
    "MEMBERSHIP",
    "Current true-member records.",
    "Member profiles",
    ["barangay", "sector"],
    [...chairmanOnly],
  ),
  report(
    "membership-fee-status",
    "Membership Fee Status",
    "MEMBERSHIP",
    "Validated and outstanding associate membership fees.",
    "Members and payment references",
    ["paymentStatus"],
    [...chairmanOnly],
  ),
  report(
    "share-capital-contributions",
    "Share-Capital Contributions",
    "MEMBERSHIP",
    "Validated share-capital payment activity.",
    "Share capital payments",
    [...standardDates, "paymentStatus"],
  ),
  report(
    "share-capital-balance",
    "Share-Capital Balance",
    "MEMBERSHIP",
    "Validated contribution totals and remaining initial capital.",
    "Members and share capital",
    ["membershipType"],
  ),
  report(
    "incomplete-initial-capital",
    "Members with Incomplete Initial Capital",
    "MEMBERSHIP",
    "True members below the confirmed ₱1,500 initial requirement.",
    "Members and share capital",
    [],
  ),
  report(
    "membership-certificates",
    "Membership Certificates Issued",
    "MEMBERSHIP",
    "Certificate documents linked to member records.",
    "Documents",
    [...standardDates],
    [...chairmanOnly],
  ),

  report(
    "rental-booking-summary",
    "Rental Booking Summary",
    "RENTAL",
    "Rental booking volume and stored approved amounts.",
    "Rental bookings and assets",
    [...standardDates, "rentalAssetId", "rentalStatus"],
  ),
  report(
    "rental-schedule",
    "Rental Schedule",
    "RENTAL",
    "Approved, scheduled, and in-use rental periods.",
    "Rental bookings and assets",
    [...standardDates, "rentalAssetId"],
  ),
  report(
    "rental-income",
    "Rental Income",
    "RENTAL",
    "Confirmed posted rental income only.",
    "Financial ledger",
    [...standardDates, "rentalAssetId"],
  ),
  report(
    "rental-payment-status",
    "Rental Payment Status",
    "RENTAL",
    "Stored booking payment states without treating inquiries as income.",
    "Rental bookings",
    [...standardDates, "rentalAssetId", "paymentStatus"],
  ),
  report(
    "rental-asset-utilization",
    "Rental Asset Utilization",
    "RENTAL",
    "Completed and scheduled bookings by asset.",
    "Rental assets and bookings",
    [...standardDates, "rentalAssetId"],
  ),
  report(
    "rental-asset-availability",
    "Rental Asset Availability",
    "RENTAL",
    "Current asset and maintenance availability state.",
    "Rental assets and maintenance",
    ["rentalAssetId"],
  ),
  report(
    "rental-expenses",
    "Rental Expenses",
    "RENTAL",
    "Confirmed posted rental expenses.",
    "Financial ledger",
    [...standardDates],
  ),
  report(
    "maintenance-history",
    "Maintenance History",
    "RENTAL",
    "Actual rental asset maintenance records and stored costs.",
    "Rental maintenance periods",
    [...standardDates, "rentalAssetId"],
  ),
  report(
    "completed-rentals",
    "Completed Rentals",
    "RENTAL",
    "Completed rental booking records.",
    "Rental bookings",
    [...standardDates, "rentalAssetId"],
  ),
  report(
    "cancelled-rentals",
    "Cancelled Rentals",
    "RENTAL",
    "Cancelled rental records and recorded reasons.",
    "Rental bookings",
    [...standardDates, "rentalAssetId"],
  ),

  report(
    "sales-summary",
    "Sales Summary",
    "SALES_INVENTORY",
    "Actual POS sale totals and statuses.",
    "POS sales",
    [...standardDates],
  ),
  report(
    "sales-by-product",
    "Sales by Product",
    "SALES_INVENTORY",
    "Completed and paid sale lines by product.",
    "POS sales and items",
    [...standardDates, "productId"],
  ),
  report(
    "sales-by-category",
    "Sales by Category",
    "SALES_INVENTORY",
    "Completed and paid sales grouped by product category.",
    "POS sales, items, and products",
    [...standardDates, "productCategory"],
  ),
  report(
    "pos-payment-status",
    "POS Payment Status",
    "SALES_INVENTORY",
    "POS transactions grouped by payment state.",
    "POS sales",
    [...standardDates, "paymentStatus"],
  ),
  report(
    "product-inventory",
    "Product Inventory",
    "SALES_INVENTORY",
    "Current stock computed from inventory movements.",
    "Products and inventory movements",
    ["productCategory"],
  ),
  report(
    "low-stock",
    "Low Stock",
    "SALES_INVENTORY",
    "Tracked products at or below their reorder level.",
    "Products and inventory movements",
    ["productCategory"],
  ),
  report(
    "bulk-orders",
    "Bulk Orders",
    "SALES_INVENTORY",
    "Actual POS transactions stored as bulk orders.",
    "POS sales",
    [...standardDates],
  ),
  report(
    "preorders",
    "Preorders",
    "SALES_INVENTORY",
    "Actual POS transactions stored as preorders.",
    "POS sales",
    [...standardDates],
  ),
  report(
    "inventory-movement",
    "Inventory Movement",
    "SALES_INVENTORY",
    "Stock movement history by product.",
    "Inventory movements",
    [...standardDates, "productId"],
  ),
  report(
    "product-expenses",
    "Product Expenses",
    "SALES_INVENTORY",
    "Confirmed posted expenses sourced from POS operations.",
    "Financial ledger",
    [...standardDates],
  ),

  report(
    "document-register",
    "Document Register",
    "DOCUMENTS",
    "Central register of cooperative files and access settings.",
    "Documents",
    [
      ...standardDates,
      "documentCategory",
      "documentAccessLevel",
      "relatedModule",
    ],
    [...chairmanOnly],
  ),
  report(
    "documents-by-category",
    "Documents by Category",
    "DOCUMENTS",
    "Document totals grouped by centralized category.",
    "Documents",
    ["documentCategory"],
    [...chairmanOnly],
  ),
  report(
    "documents-by-access",
    "Documents by Access Level",
    "DOCUMENTS",
    "Document totals grouped by server-enforced access level.",
    "Documents",
    ["documentAccessLevel"],
    [...chairmanOnly],
  ),

  report(
    "expiring-documents",
    "Expiring Documents",
    "DOCUMENTS",
    "Active documents expiring within the selected period.",
    "Documents",
    [...standardDates, "documentCategory"],
    [...chairmanOnly],
  ),
  report(
    "expired-documents",
    "Expired Documents",
    "DOCUMENTS",
    "Non-archived documents whose expiration date has passed.",
    "Documents",
    ["documentCategory"],
    [...chairmanOnly],
  ),
  report(
    "archived-documents",
    "Archived Documents",
    "DOCUMENTS",
    "Preserved archived cooperative documents.",
    "Documents",
    [...standardDates, "documentCategory"],
    [...chairmanOnly],
  ),
  report(
    "document-upload-activity",
    "Document Upload Activity",
    "DOCUMENTS",
    "Actual document uploads and uploaders.",
    "Documents and users",
    [...standardDates, "userId"],
    [...chairmanOnly],
  ),
  report(
    "document-download-history",
    "Document Download History",
    "DOCUMENTS",
    "Actual server-recorded download events.",
    "Document access logs",
    [...standardDates, "userId"],
    [...chairmanOnly],
  ),


  report(
    "user-activity",
    "User Activity",
    "AUDIT_ADMINISTRATION",
    "Material audited actions by authenticated users.",
    "Audit logs and users",
    [...standardDates, "userId", "role", "auditAction"],
    [...chairmanOnly],
  ),
  report(
    "audit-trail",
    "Audit Trail",
    "AUDIT_ADMINISTRATION",
    "System audit records and affected entities.",
    "Audit logs",
    [...standardDates, "userId", "auditAction"],
    [...chairmanOnly],
  ),
  report(
    "login-activity",
    "Login Activity",
    "AUDIT_ADMINISTRATION",
    "Successful, failed, and revoked session events.",
    "Authentication audit logs",
    [...standardDates, "userId"],
    [...chairmanOnly],
  ),
  report(
    "role-permission-summary",
    "Role and Permission Summary",
    "AUDIT_ADMINISTRATION",
    "Configured TrackCOOP roles and active account counts.",
    "Roles and users",
    ["role"],
    [...chairmanOnly],
  ),
  report(
    "notification-activity",
    "Notification Activity",
    "AUDIT_ADMINISTRATION",
    "Generated notification volume and read state.",
    "Notifications",
    [...standardDates, "userId"],
    [...chairmanOnly],
  ),
  report(
    "data-change-history",
    "Data Change History",
    "AUDIT_ADMINISTRATION",
    "Audited actions containing previous or new values.",
    "Audit logs",
    [...standardDates, "userId", "auditAction"],
    [...chairmanOnly],
  ),

  {
    key: "annual-plan-template",
    name: "Annual Plan Template",
    category: "AGENCY_COOPERATIVE",
    description: "Client-owned format has not been configured.",
    dataSource: "Template or Client Configuration Required",
    filters: ["year"],
    allowedRoles: [...chairmanOnly],
    configurationRequired: true,
  },
  {
    key: "business-plan-template",
    name: "Business Plan Template",
    category: "AGENCY_COOPERATIVE",
    description: "Client-owned format has not been configured.",
    dataSource: "Template or Client Configuration Required",
    filters: ["year"],
    allowedRoles: [...chairmanOnly],
    configurationRequired: true,
  },
  {
    key: "agency-report-template",
    name: "Agency-Specific Cooperative Report",
    category: "AGENCY_COOPERATIVE",
    description:
      "Agency form and statutory rules require client configuration.",
    dataSource: "Template or Client Configuration Required",
    filters: [...standardDates],
    allowedRoles: [...chairmanOnly],
    configurationRequired: true,
  },
];

export const REPORT_CATEGORY_LABELS: Record<
  ReportDefinition["category"],
  string
> = {
  FINANCIAL: "Financial",
  MEMBERSHIP: "Membership",
  RENTAL: "Rental",
  SALES_INVENTORY: "Sales and Inventory",
  DOCUMENTS: "Documents",
  AUDIT_ADMINISTRATION: "Audit and Administration",
  AGENCY_COOPERATIVE: "Agency and Cooperative",
};

export function accessLevelLabel(value: DocumentAccessLevel) {
  return (
    DOCUMENT_ACCESS_LEVELS.find((item) => item.value === value)?.label ?? value
  );
}

export function humanizeConstant(value: string) {
  return value
    .toLowerCase()
    .replaceAll("_", " ")
    .replace(/\b\w/g, (character) => character.toUpperCase());
}
