import { NextRequest, NextResponse } from "next/server";
import { requireApiUser } from "@/lib/next-api-auth";
import {
  listGeneratedReports,
  recordReportRegisterExport,
} from "@/features/records/server/report-service";
import {
  recordsErrorResponse,
  requestMetadata,
} from "@/features/records/server/api-response";

function cell(value: string | number | null) {
  return `"${String(value ?? "").replaceAll('"', '""')}"`;
}

export async function GET(request: NextRequest) {
  try {
    const auth = await requireApiUser(["chairman", "bookkeeper"]);
    if (auth.response) return auth.response;
    const reports = await listGeneratedReports(auth.user);
    const rows = [
      [
        "Report Reference",
        "Report",
        "Category",
        "Period",
        "Generated By",
        "Generated At",
        "Format",
        "Status",
        "Document Reference",
      ],
      ...reports.map((report) => [
        report.reference,
        report.title,
        report.category,
        report.periodLabel,
        report.generatedBy,
        report.generatedAt,
        report.outputFormat,
        report.status,
        report.documentReference,
      ]),
    ].map((row) => row.map(cell).join(","));
    await recordReportRegisterExport(auth.user, requestMetadata(request));
    return new NextResponse(`\uFEFF${rows.join("\r\n")}`, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="trackcoop-report-register-${new Date().toISOString().slice(0, 10)}.csv"`,
        "Cache-Control": "private, no-store",
      },
    });
  } catch (error) {
    return recordsErrorResponse(error);
  }
}
